### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by edahlseng** [pointfreeco/swift-prelude#111]
It seems like there's a lot of documentation missing for this library (or at least I couldn't find it). I'd love to help out with the documentation, if that's needed! Where would we want it kept (i.e., in the README, or in other files, linked from the README)? Is there anything else that you'd like me to keep in mind before contributing?

**Comment by normand1** [comment]
There are a lot of operators here that are implemented by this library, but have no documentation. Is there an easy place to learn about what these operators do and what some basic use cases for them might be?

**Comment by stephencelis** [comment]
We have always considered this repo to be raw/experimental/unstable, so it hasn't been given the affordances of things like documentation. We've also slowed down iteration on it in favor of more refined tools that fit in more nicely with Swift. Going to close this out since we don't intend to address the lack of documentation, but if there are any specific parts of the repo that you have questions about, please feel free to start a GitHub discussion!
